CC = gcc
PROGRAM = server
CFLAGS = -Wall
#CFLAGS = -g -O2 -Wall -ansi -pedantic
LFLAGS =
#LFLAGS = -L libkatalog -lm -lfoo -lbar
SOURCE = server.c
$(PROGRAM): $(SOURCE)
	$(CC) $(CFLAGS) $(SOURCE) $(LFLAGS) -o $(PROGRAM)

